#ifndef __CLOX_OPS_H__
#define __CLOX_OPS_H__

#define EXT_CODE_SZ (sizeof(char) * 3)
#define EXT_CODE_MASK (0x00ffffff)

typedef enum {
	OP_CONSTANT,
	OP_CONSTANT_LONG,
	OP_EQUAL,
	OP_GREATER,
	OP_LESS,
	OP_NIL,
	OP_TRUE,
	OP_FALSE,
	OP_NOT,
	OP_ADD,
	OP_SUBTRACT,
	OP_MULTIPLY,
	OP_DIVIDE,
	OP_NEGATE,
	OP_PRINT,
	OP_POP,
	OP_GLOBAL_DEFINE,
	OP_GLOBAL_DEFINE_LONG,
	OP_GLOBAL_GET,
	OP_GLOBAL_GET_LONG,
	OP_GLOBAL_SET,
	OP_GLOBAL_SET_LONG,
	OP_RETURN
} op_code_t;

#endif // __CLOX_OPS_H__
