/**
 * @file ops_table.h
 * @author Dylan Mayor
 * @brief X define header file which holds information about vm operations and their display names.
 * Used to populate op name and function defines whilst keeping opcode information in one place
 *
 * @see ops_name.h
 * @see ops.h
 *
 */
#define XX(op) X(op, #op)

XX(OP_NOP)
XX(OP_CONSTANT)
XX(OP_CONSTANT_LONG)
XX(OP_CLOSURE)
XX(OP_CLOSURE_LONG)
XX(OP_EQUAL)
XX(OP_GREATER)
XX(OP_LESS)
XX(OP_NIL)
XX(OP_TRUE)
XX(OP_FALSE)
XX(OP_NOT)
XX(OP_ADD)
XX(OP_MOD)
XX(OP_SUBTRACT)
XX(OP_MULTIPLY)
XX(OP_DIVIDE)
XX(OP_NEGATE)
XX(OP_POP)
XX(OP_POP_COUNT)
XX(OP_VAR_DEFINE)
XX(OP_VAR_DEFINE_LONG)
XX(OP_VAR_GET)
XX(OP_VAR_GET_LONG)
XX(OP_VAR_SET)
XX(OP_VAR_SET_LONG)
XX(OP_GLOBAL_DEFINE)
XX(OP_GLOBAL_DEFINE_LONG)
XX(OP_GLOBAL_GET)
XX(OP_GLOBAL_GET_LONG)
XX(OP_GLOBAL_SET)
XX(OP_GLOBAL_SET_LONG)
XX(OP_UPVALUE_GET)
XX(OP_UPVALUE_GET_LONG)
XX(OP_UPVALUE_SET)
XX(OP_UPVALUE_SET_LONG)
XX(OP_UPVALUE_DEFINE)
XX(OP_UPVALUE_DEFINE_LONG)
XX(OP_CLOSE_UPVALUE)
XX(OP_JUMP)
XX(OP_JUMP_IF_FALSE)
XX(OP_CALL)
XX(OP_RETURN)

#undef XX